<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>acadbot_localization</name>
  <version>1.0.0</version>
  <description>C++ localization node for AcadBot: monitors AMCL convergence on a saved map.</description>
  <maintainer email="tarabayhiba05@gmail.com">Hiba Tarabay</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>acadbot_gazebo</exec_depend>
  <exec_depend>acadbot_navigation</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
